import 'package:flutter/material.dart';

class AppTheme {
  static ThemeData lightTheme = ThemeData(
    useMaterial3: true,
    brightness: Brightness.light,
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF006686),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFC0E8FF),
      onPrimaryContainer: Color(0xFF001E2B),
      secondary: Color(0xFF006875),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFF9AF0FF),
      onSecondaryContainer: Color(0xFF001F24),
      tertiary: Color(0xFF00658C),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFC6E7FF),
      onTertiaryContainer: Color(0xFF001E2D),
      error: Color(0xFFBA1A1A),
      onError: Color(0xFFFFFFFF),
      errorContainer: Color(0xFFFFDAD6),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFAFCFF),
      onBackground: Color(0xFF001F2A),
      surface: Color(0xFFFAFCFF),
      onSurface: Color(0xFF001F2A),
      surfaceVariant: Color(0xFFDCE3E9),
      onSurfaceVariant: Color(0xFF40484C),
      outline: Color(0xFF71787D),
      shadow: Color(0xFF000000),
      inverseSurface: Color(0xFF003547),
      onInverseSurface: Color(0xFFE1F4FF),
      inversePrimary: Color(0xFF70D2FF),
      surfaceTint: Color(0xFF006686),
    ),
  );

  static ThemeData darkTheme = ThemeData(
    useMaterial3: true,
    brightness: Brightness.dark,
    colorScheme: const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF70D2FF),
      onPrimary: Color(0xFF003547),
      primaryContainer: Color(0xFF004D66),
      onPrimaryContainer: Color(0xFFC0E8FF),
      secondary: Color(0xFF50D8EC),
      onSecondary: Color(0xFF00363D),
      secondaryContainer: Color(0xFF004F58),
      onSecondaryContainer: Color(0xFF9AF0FF),
      tertiary: Color(0xFF81CFFF),
      onTertiary: Color(0xFF00344B),
      tertiaryContainer: Color(0xFF004C6B),
      onTertiaryContainer: Color(0xFFC6E7FF),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF93000A),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF001219),
      onBackground: Color(0xFFBFE9FF),
      surface: Color(0xFF001219),
      onSurface: Color(0xFFBFE9FF),
      surfaceVariant: Color(0xFF40484C),
      onSurfaceVariant: Color(0xFFC0C7CD),
      outline: Color(0xFF8A9297),
      shadow: Color(0xFF000000),
      inverseSurface: Color(0xFFBFE9FF),
      onInverseSurface: Color(0xFF001F2A),
      inversePrimary: Color(0xFF006686),
      surfaceTint: Color(0xFF70D2FF),
    ),
  );
}